name: s1-orbits
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For packaging, and testing
  - build
  - setuptools>=61
  - setuptools_scm>=6.2
  - pytest
  - pytest-cov
  - responses
  # For running
  - requests
